openapi: 3.0.0
info:
  title: GeoLocation API Docs
  version: 1.0.0
components:
  schemas:
paths:
  /home:
    get:
      tags:
       - Home
      description: Home page
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string
  
  /city/{ip}:
    get:
      tags:
        - City
      summary: Get GeoLocation in JSON
      parameters:
        - name: ip
          in: path
          description: IP address
          required: true
          schema:
            type: string

        - name: fields
          in: query
          description: Comma-separated list of fields to include in response
          required: false
          schema:
            anyOf:
              - type: array
                items:
                  type: string
              - type: integer
                format: int32

        - name: lang
          in: query
          description: Language code
          required: false
          schema:
            type: string

        - name: callback
          in: query
          description: Callback function name for JSONP response
          required: false
          schema:
            type: string

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeoLocationResponseObject'
        '301':
          description: Moved Permanently
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: Redirect URL to a new, randomly generated domain
        '404':
          description: Not Found
        '429':
          description: Too Many Requests

  /city/xml/{ip}:
    get:
      tags:
        - City
      summary: Get GeoLocation in XML
      parameters:
        - name: ip
          in: path
          required: true
          schema:
            type: string
          description: IPv4/IPv6 address or domain name

        - name: fields
          in: query
          required: false
          schema:
            anyOf:
              - type: array
                items:
                  type: string
              - type: integer
                format: int32
          description: Custom fields (optional)

        - name: lang
          in: query
          required: false
          schema:
            type: string
          description: Response language (optional)

      responses:
        '200':
          description: Successful response (XML)
          content:
            application/xml:
              schema:
                type: string
        '404':
          description: Not Found
        '429':
          description: Too Many Requests

  /city/csv/{ip}:
    get:
      tags:
        - City
      summary: Get GeoLocation in CSV
      parameters:
        - name: ip
          in: path
          required: true
          schema:
            type: string
          description: IPv4/IPv6 address or domain name
        - name: fields
          in: query
          required: false
          schema:
            type: integer
          description: Custom fields (optional)
        - name: lang
          in: query
          required: false
          schema:
            type: string
          description: Response language (optional)
        - name: header
          in: query
          required: false
          schema:
            type: boolean
          description: Include field header (optional)
      responses:
        '200':
          description: Successful response (CSV)
          content:
            text/csv:
              schema:
                type: string
        '404':
          description: Not Found
        '429':
          description: Too Many Requests

  /city/line/{ip}:
    get:
      tags:
        - City
      summary: Get GeoLocation in NewLine
      parameters:

        - name: ip
          in: path
          required: true
          schema:
            type: string
          description: IPv4/IPv6 address or domain name

        - name: fields
          in: query
          required: false
          schema:
            type: integer
          description: Custom fields (optional)

        - name: lang
          in: query
          required: false
          schema:
            type: string
          description: Response language (optional)

      responses:
        '200':
          description: Successful response (Line format)
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Not Found
        '429':
          description: Too Many Requests

  /batch:
    post:
      tags:
        - Batch
      summary: Get GeoLocation for a batch of IPs
      parameters:
        - name: fields
          in: query
          description: Comma-separated list of fields to include in response
          required: false
          schema:
            anyOf:
              - type: array
                items:
                  type: string
              - type: integer
                format: int32

        - name: lang
          in: query
          description: Language code
          required: false
          schema:
            type: string

      requestBody:
        description: Batch request body
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BatchRequestObject'

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeoLocationResponseObject'
        '301':
          description: Moved Permanently
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: Redirect URL to a new, randomly generated domain
        '404':
          description: Not Found
        '429':
          description: Too Many Requests

  /dns:
    get:
      summary: Get DNS and EDNS Info
      tags:
        - DNS
      parameters:
        - name: callback
          in: query
          description: Callback function name for JSONP response
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DnsResponseObject'
        '301':
          description: Moved Permanently
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: Redirect URL to a new, randomly generated domain
        '404':
          description: Not Found
        '429':
          description: Too Many Requests
  /georev:
    get:
      description: 'Converts geographic coordinates into a human-readable address or place name'
      parameters: 
        - in: query
          name: lat
          schema: 
            type: integer
          description: 'Latitude for reverse geo-coding'
        - in: query
          name: lon
          schema: 
            type: integer
          description: 'Longitude for reverse geo-coding'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/GeoLocationResponseObject'