name: Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./geoip # Set the path to your project root directory

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.23
        
      
      - name: Install dependencies
        run: bun install
        working-directory: ./geoip/server # Set the working directory to your project root

      - name: Run bun test
        run: bun test
        working-directory: ./geoip/server # Set the working directory to your project root
